# Generated by Django 4.1 on 2023-07-18 05:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analiticaSiniestros", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Siniestro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gravedad", models.FloatField()),
                ("claseSiniestro", models.FloatField()),
                ("choque", models.FloatField()),
                ("codigoLocalidad", models.FloatField()),
                ("disenoLugar", models.FloatField()),
                ("condicion", models.FloatField()),
                ("estado", models.FloatField()),
                ("edad", models.FloatField()),
                ("sexo", models.FloatField()),
                ("claseVehiculo", models.FloatField()),
                ("servicio", models.FloatField()),
                ("enfuga", models.FloatField()),
                ("codigoCausa", models.FloatField()),
                ("fechaHora", models.DateTimeField()),
            ],
        ),
    ]
