# Generated by Django 4.1 on 2023-08-23 04:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analiticaSiniestros", "0002_siniestro"),
    ]

    operations = [
        migrations.CreateModel(
            name="Choque",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("idChoque", models.FloatField()),
                ("DescChoque", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="ClaseSiniestro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("idClaseSiniestro", models.FloatField()),
                ("DescClaseSiniestro", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="ClaseVehiculo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("idClaseVehiculo", models.FloatField()),
                ("DescClaseVehiculo", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="CodigoCausa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("idCodigoCausa", models.FloatField()),
                ("DescCodigoCausa", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="CodigoLocalidad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("idCodigoLocalidad", models.FloatField()),
                ("DescCodigoLocalidad", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Condicion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("idCondicion", models.FloatField()),
                ("DescCondicion", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="DisenoLugar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("idDisenoLugar", models.FloatField()),
                ("DescDisenoLugar", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Enfuga",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("idEnfuga", models.FloatField()),
                ("DescEnfuga", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Estado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("idEstado", models.FloatField()),
                ("DescEstado", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Gravedad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("idGravedad", models.FloatField()),
                ("DescGravedad", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Servicio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("idServicio", models.FloatField()),
                ("DescServicio", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Sexo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("idSexo", models.FloatField()),
                ("DescSexo", models.FloatField()),
            ],
        ),
    ]
