# Generated by Django 4.1 on 2023-08-23 04:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "analiticaSiniestros",
            "0003_choque_clasesiniestro_clasevehiculo_codigocausa_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="choque",
            name="DescChoque",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="clasesiniestro",
            name="DescClaseSiniestro",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="clasevehiculo",
            name="DescClaseVehiculo",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="codigocausa",
            name="DescCodigoCausa",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="codigolocalidad",
            name="DescCodigoLocalidad",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="condicion",
            name="DescCondicion",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="disenolugar",
            name="DescDisenoLugar",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="enfuga",
            name="DescEnfuga",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="estado",
            name="DescEstado",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="gravedad",
            name="DescGravedad",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="servicio",
            name="DescServicio",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="sexo",
            name="DescSexo",
            field=models.CharField(max_length=200),
        ),
    ]
